lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    pass_phrase: '%env(JWT_PASSPHRASE)%' # required for token creation
    # ttl => time to live, d√©lai expiration
    # 64800 = 18h
    token_ttl: 64800 # in seconds, default is 3600
